### ISSUE TITLE
Imu and Encoder fusion question 

### ISSUE THREAD

**Issue by saimouli** [locusrobotics/fuse#179]
I have created a static publisher frame called "world" to transform all the sensor measurements (IMU and encoder) into the world frame before fusing. Please see the attached frames.pdf. 
![tbDemo](https://user-images.githubusercontent.com/14081959/79671685-445b4400-819a-11ea-8797-3b0403461511.png)

I get the following errors: 

> [ WARN] [1587245697.790895414, 14458.245000000]: No valid state data yet. Delaying tf broadcast.

> [ERROR] [1587245697.811071435, 14458.266000000]: Invalid partial absolute pose measurement from 'imu_sensor' source: Invalid partial mean [-nan]
> 
> [ERROR] [1587245697.812112254, 14458.267000000]: Invalid partial angular velocity measurement from 'imu_sensor' source: Invalid partial mean [-nan]
> 
> [ERROR] [1587245697.812920705, 14458.267000000]: Invalid partial linear acceleration measurement from 'imu_sensor' source: Invalid partial mean [-nan]
> [-nan]

Turns out I get nan values after the transformation inside the function `bool transformMessage(const tf2_ros::Buffer& tf_buffer, const T& input, T& output)` possible that world frame transformation does not exist. To test I changed the target_frame to be the base_footprint and as expected I don't get nan values, but covar. is non positive definite. 

I get the following errors: 

> `[ WARN] [1587244909.151203910, 13670.531000000]: No valid state data yet. Delaying tf broadcast.
> [ERROR] [1587244909.165917967, 13670.545000000]: Invalid partial absolute pose measurement from 'imu_sensor' source: Non-positive-definite partial covariance matrix
> [0]
> 
> [ERROR] [1587244909.167231158, 13670.546000000]: Invalid partial angular velocity measurement from 'imu_sensor' source: Non-positive-definite partial covariance matrix
> [0]
> 
> [ERROR] [1587244909.171330343, 13670.551000000]: Invalid partial linear acceleration measurement from 'imu_sensor' source: Non-positive-definite partial covariance matrix
> [0, 0]
> [0, 0]
> 
> [ERROR] [1587244909.189903674, 13670.569000000]: Invalid partial linear velocity measurement from 'encoder_sensor' source: Non-positive-definite partial covariance matrix
> [0, 0]
> [0, 0]`
> 

Questions: 
1. Is it vaid transforming IMU and encoder measurements into the world frame before fusing? It does not make sense if IMU measurements are in base_footprint (robot body frame) and encoder's in "odom" frame. 

2. Should the imu and encoder measurements covariance be non-zero when published to ros? For example: rostopic echo /imu gives 

> header: 
>   seq: 12477
>   stamp: 
>     secs: 14962
>     nsecs:  36000000
>   frame_id: "base_footprint"
> orientation: 
>   x: 0.0015566085891899162
>   y: 0.0003276490868402762
>   z: -0.9788036429173815
>   w: 0.2047947709963295
> orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
> angular_velocity: 
>   x: -0.0005358902335171238
>   y: -0.0003909577325524005
>   z: 0.19488579839896925
> angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
> linear_acceleration: 
>   x: 5.083136873524716e-05
>   y: 0.00010048728744395968
>   z: 2.618836550644121e-07
> linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

**Comment by svwilliams** [comment]
There are potentially many questions here. I'll do my best.

Let's start with the easy question first.
Question #2: Should the imu and encoder measurements covariance be non-zero?
Yes. fuse uses the covariance information provided in these messages to weight the influence of each input on the final state estimate. These fields must be populated with valid covariance information, where "valid" means strictly positive-definite and meaningfully describing the accuracy of the sensor.

And now on to a very long discussion for Question #1: What frames should be used when transforming sensor data?

First, I just want to point you at the standard ROS frame conventions.
https://www.ros.org/reps/rep-0105.html
The frames you posted above do not conform to a typical system. Specifically, the world frame is linked directly to the base_footprint frame. Typically the world/map frame would link to the odom frame, and the odom frame would link to the base_footprint/base_link frame. map -> odom -> base_link, or world -> odom -> base_footprint in your case.

Second, I'm not sure precisely what output you are trying to achieve. There are two typical usages:
1) My robot has several dead-reckoning types of sensors, and I'd like to combine them to create a better dead-reckoning result. The result is often published to tf as the odom -> base_link transform. 
2) I have several sensors on my robot, and some of them provide me with an absolute position in some global frame. For example, a GPS sensor or laser scan matching to a prior map. I want to fuse all of my sensor data to produce the best estimate of the robot in the global frame. The result is often published to tf as the map -> odom transform.

Note that in addition to estimating the robot pose in one of the chosen frames, we typically also estimate the body frame velocity and acceleration of the robot. These quantities will be represented in the base_link frame (or base_footprint frame for you).

Since you are fusing IMU and wheel encoder data, and neither of them provide information in a global frame, I'm going to assume you are trying to achieve Usage 1 above.

To start answering the "What frames should be used when transforming sensor data?" question, let's begin with the IMU.

A typical IMU directly measures the linear acceleration and angular velocity of the IMU sensor frame, "imu_link" in your frame tree. (I'm ignoring the fact that the IMU message you posted has it listed in the "base_footprint" frame. That's just weird, and probably an artifact of Gazebo. A real sensor should produce measurements in the sensor's own frame.) However, what you want is the linear acceleration and angular velocity of the robot body frame, "base_footprint". This is done by setting the "acceleration_target_frame" parameter and the "twist_target_frame" of the "fuse_models::Imu2D" sensor model to "base_footprint". This sets the transformation target frame for the linear acceleration and angular velocity respectively.

In addition to providing the directly measured values, the IMU message also includes derived values. The IMU may integrate the angular velocity measurements and report an orientation. This is where life gets interesting. The Earth's gravity is often used as a reference in IMU processing, making it possible to estimate roll and pitch of the IMU accurately. This would be a measurement in a global frame. However, 2D robot's don't roll or pitch, so that is largely meaningless. The yaw, on the other hand, will be in some sort of "IMU dead reckoning" frame. Wherever the robot was powered-on, that likely became the origin of this "IMU dead reckoning" frame. As new IMU measurements are received, the IMU's yaw in this frame will get updated. Like any dead-reckoning frame, the yaw of the IMU will drift relative to its absolute pose in some real world frame. This drift is independent of any other dead reckoning frame that may exist (like the encoders). This makes using the IMU yaw information difficult. You _can_ choose to use the IMU yaw information directly, but that is very unlikely what you want to do. What makes more sense is computing a _change_ in yaw in the IMU frame. i.e. You don't want to tell fuse "The IMU says the robot yaw is 2.13rad". Instead you want to tell fuse "The IMU says the robot yaw changed 0.12rad clockwise". How the orientation information is used is controlled by the "differential" parameter of the "fuse_models::Imu2D" sensor model. If "differential" is false, the yaw information will be used directly. If "differential" is true, the change in yaw will be used instead. If you use "differential" mode, the sensor data should be transformed into the robot body frame, "robot_footprint". This is controlled by the "orientation_target_frame" parameter.

Also note that which pieces of IMU data are used can also be configured. The "linear_acceleration_dimensions", "angular_velocity_dimensions", and "orientation_dimensions" parameters can be populated with a list of strings specifying which dimensions to use The values "x" and "y" are supported for the linear properties, and "yaw" is supported for the angular properties. And empty set means don't use any measurements for that group.

To sum up, a bare-bones config might look like:
```
imu_sensor:
  linear_acceleration_dimensions: ['x', 'y']
  acceleration_target_frame: base_footprint
  angular_velocity_dimensions: ['yaw']
  twist_target_frame: base_footprint
```
And if you want to use the reported IMU yaw, then:
```
imu_sensor:
  linear_acceleration_dimensions: ['x', 'y']
  acceleration_target_frame: base_footprint
  angular_velocity_dimensions: ['yaw']
  twist_target_frame: base_footprint
  orientation_dimensions: ['yaw']
  orientation_target_frame: base_footprint
  differential: true
  independent: false
```

The encoder nav_msgs::Odometry message is very similar. It includes the robot's linear and angular velocity, as well as the robot's position and orientation in an "encoder dead reckoning" frame. Just like the IMU, the encoder velocities should be transformed into the robot's body frame, "robot_footprint" for you. And just like the IMU, the encoder's position and orientation should not be used directly. Instead it should be configured as a "differential" source.

So an encoder config might look like:
```
encoder_sensor:
  linear_velocity_dimensions: ['x']
  angular_velocity_dimensions: ['yaw']
  twist_target_frame: base_footprint
  position_dimensions: ['x', 'y']
  orientation_dimensions: ['yaw']
  pose_target_frame: base_footprint
  differential: true
  independent: false
```

And finally, a note on the log messages:
> No valid state data yet. Delaying tf broadcast.

That means that the odometry publisher plugin has not received any data from the optimizer yet, so it is not publishing anything to tf yet.

> Invalid partial linear acceleration measurement from 'imu_sensor' source: Non-positive-definite partial covariance matrix

That means the covariance in the received sensor message is not valid. When that happens, that measurement is not processed and not sent to the optimizer.

> Invalid partial absolute pose measurement from 'imu_sensor' source: Invalid partial mean [-nan]

And that means the pose in the received sensor message is not valid. When that happens, that measurement is not processed and not sent to the optimizer. I'll be honest, I didn't know tf would return NaNs if it couldn't transform data. I'll have to look into that one.

Let me know if any of that doesn't make sense, or you need more clarification on something. I'm happy to help.
